glPortal test elements
- Portals (eh!)
  * Keeping forward momentum, or, to be more precise, how it does not.
- Boxes
  * Constructed in-place (materialization or assembly, the latter is harder to animate but way cooler)
- Lasers
  ! Red laser is for the weak, has short wavelength. Give us blue/purple lasers!
  * Can have speed of light OR be slown down by emitter (see upcoming 3D model)
  * Purple lasers are lethal and can be used to (willingly) damage things, whereas blue ones are not
    (both can be, of course, used to activate laser receivers)
- Laser redirection boxes
- Buttons
  * Player activated (small button)
  * Box activated
- Gravity fields
  * Changes gravity for a given zone
  ?! Can we let players go in them? Can cause issues or complexify code, e.g. regarding portal placement orientation
- Projected gravity fields
  * Same as above, but projected, can go through portals, and has velocity cap
- Air ducts
  * Blow air or suck air, can be used to attract/repel objects
- Catapults
  * Target
- Fizzlers
  - Portal-only
  - Object-only
  - Both
  * Visible action surface (another Simplex Noise?) / volume edge
  * Edges visible and surrounded by wall-tied emitters
    * Might be sticking out of the wall or part of it

Other design-related things
- Show connection between elements by lines on the wall
  * Show logical operations using their respective MIL/ANSI symbol,
    plus its short name (AND, OR, NAND, NOR, XOR, XNOR, NOT) inside the symbol
    (because not everyone knows the symbol)
  * Has a to-be-chosen color when disabled, anoter one when enabled
  * Can have delay gates
    * Must choose a symbol
    * Delay written in symbol (e.g. 2s)

(Advanced) theme rooms/test series
Elemental series
- Water/other liquid  - !! Requires specific test chamber design to avoid too much sandboxing if the flow simulation is costly !!
  * Could be poured by portals from a container/dispenser to fill some areas requiring fill-up as part of the test
  * Use drains to limit liquid quantity
- Fire & hot Air
  * Can make wooden objects catch fire to clean a path
  * Its hot air effect (non-physically simulated, but still visually displayed using particles) could lift things (c.f. hot air balloons)
- Earth? Give ideas.
- Heat/cold beams (maybe?)
  * Could lead to funny mechanics like triggering fire, making water boil/freeze it
    * Freezing electrified, albeit deadly, water to be able to walk on it

Wavelength series
- Colored Boxes for use with ↓
- Colored Box Button

- White/colored lasers
  * Has a limited set of colors:
      [Color] [RGB]
    - Red      100
    - Yellow   110
    - Green    010
    - Cyan     011
    - Blue     001
    - Purple   101
    - White    111
- Colored Laser reditection boxes
  * Acts as light filter; e.g. red laser doesn't pass through green box which only lets green pass
+ Laser reditection boxes, colored or not:
  * When combining multiple laser colors, they RGB-ically combine (e.g. Red+Cyan=White)
  * Already-imposed restrictions still applies for colored redirection boxes
- Prism?
  * Splits out laser into its R, G, B components
- Colored laser receiver
  * Can be activated by a combination of wavelengths/RGB components,
    though multiple activators are to be used only in most advanced tests
!!! On lasers: keep lethality or not? Rule(s) which defines it? !!!

Multiplicity series
- Multiple portal pairs (isn't good for colorblind people)
  * Linked portals have almost the same color:
    - Red/Orange
    - Yellow/Lime
    - Green/Blue-Green or Cyan
    - Blue/Violet

Escher series
- Noneucliean space: have (invisible) world-portals
  * Might, by far, be the hardest thing to implement because of implications (LOD, portal rendering, ...)
+ Big combination with gravity fields

Tag series
- Paint fluids
  * If Elemental series' water pouring mecanics gets implemented, can be used with paint as liquid, for storage only parts
    * Could spice up gameplay by limiting amount of paint; but resetting involves tricky things, pick one:
      - Level restart (through disintegrating you? Or through escape ways to cloned test chamber?)
      - Reset button: go to the test's start point, press reset button, water sprayers washes out paint, boxes fizzled, game mechanics' states reset
  - Speed
  - Surface-convert (nonportallable → portallable)
  - Laser-reflect

Ultimate/OCD series
* Any of the above, combined
  * "Any", possibly "All", but don't go too far
  * Not necessarily complicated, but complex (refer to the Python lore; run your Python interpreter and type "import this")
    * Actually, try to avoid complicated levels, keep the fun

Chronos series? (wibbly-wobbly timey-wimey stuff)

