* The Cog In The Machine
The Cog In The Machine is a script for the free and open 3D action adventure GlPortal.
** Technical limitations
GlPortal is an engine in progress. That means that the story telling is limted to what the engine can do.

*** Current status
The following things are possible with the current engine
- Walk around and Jump
- Portal placement on special walls on the map
- Teleportation between portals
- Triggers for health loss, death etc. on the map
- A door labeled exit that leads to the next level
*** Near future
Some features that are usefull for story telling, but are not there yet.
- Triggers that open doors and remove walls
- Objects that can be repaired as part of a mission
- buttons
- Triggers that play sounds/voice
- Parent levels that connect many smaller levels with each other.
If you need any of these features for your script to work please contact the development department.
** How to write a script
Submit early and submit often. Be aware of the technical limitations and give as much feedback as possible
to the developers so we can rush the features your story needs. Keep it simple, don't be afraid to have
a lot of gameplay in the first levels/scripts you design. We want to create the more advanced levels and 
stories at a later point in development when the engine is richer in features and our skills in creating
maps have improved. Don't bother too much with the big picture in the begining. We don't need it yet
to get practice with levels and create the 0.1 release.
** Phase I
This is a collection of ideas in preparation of phase II of the script creation.
*** Characters
**** Ada
Ada is the silten protagonist of the story. 
**** Alan
**** Lab Assistant
**** Computer
**** Prof. Huxley
*** Locations
**** Faculty
The player will be able to explore different labs like computer science, engineering and math.
There are huge complexes for generating energy for experiments and a vast network of maintneance and
waste disposal tunnels.
*** Events
**** General
Ada will improve her skills while she strugles with a lot of new tasks.
She will uncover a secret about her past and she will make new friends on
the way.
**** Detailed
***** Training
Ada gets to know her new tasks. It is not her first day so there are some things
she already is familiar with.
***** Work
***** Escalation
Nobody anticipated this. Everything goes wrong and Ada is the only around to fix it.
*** Topics
**** Fundamental Particle
Every time you find one, you kind of have the idea that it must be made up of smaller ones.
**** Space Exploration
Moon base and Mars landing.
**** Thermonuclear Reactor
Bringing the sun down to earth.
**** Newton's laws of motion
Get your dose of classical mechanics.
** Phase II
*** Chapter Outline
**** You are fired
This is the chapter where the protagonist is getting fired but proves herself valuable to a new employer.
** Phase III 
