* The Cog In The Machine
The Cog In The Machine is a script for the free and open 3D action adventure GlPortal.
** Phase I
This is a collection of ideas in preparation of phase II of the script creation.
*** Characters
**** Ada
**** Alan
**** Lab Assistant
**** Computer
**** Prof. Huxley
*** Locations
**** Faculty
The player will be able to explore different labs like computer science, engineering and math.
There are huge complexes for generating energy for experiments and a vast network of maintneance and
waste disposal tunnels.
*** Events
**** General
Ada will improve her skills while she strugles with a lot of new tasks.
She will uncover a secret about her past and she will make new friends on
the way.
**** Detailed
***** Training
Ada gets to know her new tasks. It is not her first day so there are some things
she already is familiar with.
***** Work
***** Escalation
Nobody anticipated this. Everything goes wrong and Ada is the only around to fix it.
*** Topics
**** Fundamental Particle
Every time you find one, you kind of have the idea that it must be made up of smaller ones.
**** Space Exploration
Moon base and Mars landing.
**** Thermonuclear Reactor
Bringing the sun down to earth.
** Phase II
** Phase III 
