* The Cog In The Machine
The Cog In The Machine is a script for the free and open 3D action adventure GlPortal.
** Phase I
This is a collection of ideas in preparation of phase II of the script creation.
*** Characters
**** Ada
Ada is the silent protagonist of the story. 

She starts out as a technician for the faculty. Welding and fixing equipment but later
develops her role when she realizes that she can be whatever she wants to be.

Prof. Huxley sees her potential and when she gets fired hires her back. Not as a technician
but as his assistant.

**** Alan
**** Lab Assistant
**** Computer
**** Prof. Huxley
*** Locations
**** Faculty
The player will be able to explore different labs like computer science, engineering and math.
There are huge complexes for generating energy for experiments and a vast network of maintneance and
waste disposal tunnels.
*** Events
**** General
Ada will improve her skills while she strugles with a lot of new tasks.
She will uncover a secret about her past and she will make new friends on
the way.
**** Detailed
***** Training
Ada gets to know her new tasks. It is not her first day so there are some things
she already is familiar with.
***** Work
***** Escalation
Nobody anticipated this. Everything goes wrong and Ada is the only around to fix it.
*** Topics
**** Fundamental Particle
Every time you find one, you kind of have the idea that it must be made up of smaller ones.
**** Space Exploration
Moon base and Mars landing.
**** Thermonuclear Reactor
Bringing the sun down to earth.
**** Newton's laws of motion
Get your dose of classical mechanics.
** Phase II
*** Chapter Outline
**** You are fired
This is the chapter where the protagonist is getting fired from the faculty. She is not given any reason.
On her way out she proves herself valuable to a new employer a professor of the physics department.
** Phase III 
